### ISSUE TITLE
Nightmare calling .blur() after elements removed from DOM

### ISSUE THREAD

**Issue by willclarktech** [LikeJasper/elm-boilerplate#3]
From edit-todo e2e test: when enter is pressed for the inline text input, it's removed from the DOM, but nightmare is calling blur. Currently suppressing the error here: https://github.com/LikeJasper/elm-boilerplate/blob/f49f2d2b4646ed604cf6dd6e4b91d348f3b2f94c/test-e2e/page-objects/Base.page.js#L74-L77

Relevant issue in Nightmare repo: https://github.com/segmentio/nightmare/issues/762

**Comment by rosshinkley** [comment]
Thanks for linking this issue, the element being removed before `.blur()` is called is certainly a possibility, especially with `Nightmare.type()`.  I'll put it on my list of things to look into and add tests for.
